volumes:
  mysql-db-primary:
    driver: local

networks:
  localnetwork:
    driver: bridge

services:
  database:
    container_name: mysql-db-primary
    hostname: mysql-db-primary
    build:
      context: ./platform/images/mysql
      dockerfile: MySQL.Dockerfile
    restart: on-failure
    ports:
      - 3306:3306
    command: --authentication_policy=mysql_native_password
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-db-primary:/var/lib/mysql
      - ./mysql-db-primary/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./platform/images/mysql/primary.conf.d/mysql.cnf:/etc/my.cnf
    networks:
      - localnetwork

  api:
    build: .
    container_name: api
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}/${MYSQL_DATABASE}
    volumes:
      - .:/src
    networks:
      - localnetwork
